# Site wide configuration

title: Raising Kids in Hong Kong
description:
logo: # 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale: zh-CN
url: http://www.raisingkidsinhk.tk

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Qu Xiaofeng
  email: quxiaofeng@live.com
  twitter: quxiaofeng
  google:
    ad-client: 
    ad-slot: 
  bio: A father of two Hong Kong Kids
  avatar: bio-photo.jpg # 160x160 px image for author byline
disqus-shortname: csxfqu


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
